### ISSUE TITLE
DLL injection error?

### ISSUE THREAD

**Issue by uagvaq** [FUFUGUA/GorillaLoader#1]
Hey man, i just wanted to let you know that when i try to inject the loader in it says "Injection successful!" but the game open it freezes up and crashes. I have everything in the right folders but i don't know what's happening. 

Thanks, chqalie

**Comment by FUFUGUA** [comment]
Oh lol, sorry for not answering, but try injecting with the new GorillaMaintainer.exe, or hmm, I'm not currently waiting up for the Team Fortress 2 to fully load before injecting to it, so that could cause the error you're getting, just inject it whenever your TF2 has fully loaded.
I'll approach the injecting on another way for the new releases of GorillaMaintainer, will make it like it will wait until the game has loaded.

**Comment by FUFUGUA** [comment]
https://github.com/FUFUGUA/GorillaLoader/assets/97225465/cb1d081c-2f96-4cb3-8203-c146f88ad800
